version: '3.6'
services:
  registration_db:
    image: mysql:5.7
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=mits
     - MYSQL_USER=mits
     - MYSQL_PASSWORD=mits
    volumes:
     - mits_data:/var/lib/mysql
volumes:
  mits_data:
