version: '3.6'
services:
  registration_db:
    image: mysql:5.7
    ports:
     - "3302:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=mist_registration
     - MYSQL_USER=mits
     - MYSQL_PASSWORD=mits
    volumes:
     - mits_registration_data:/var/lib/mysql
  resource-management-db:
      image: mysql:5.7
      ports:
       - "3301:3306"
      environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=mist_resource_management
       - MYSQL_USER=mits
       - MYSQL_PASSWORD=mits
      volumes:
       - mist_resource_management_data:/var/lib/mysql

volumes:
  mits_registration_data:
  mist_resource_management_data:
